### ISSUE TITLE
Grunt task completes before processing is finished

### ISSUE THREAD

**Issue by andyinabox** [dharFr/grunt-wkhtmltopdf#11]
I've noticed that there is a delay between when the task is complete and when the actual PDF file is finished being generated. It seems this could be fixed using [`this.async`](http://gruntjs.com/api/inside-tasks) within the Grunt task ([usage example](https://quickleft.com/blog/grunt-js-custom-tasks/)).

**Comment by dharFr** [comment]
Fixed by #12
