### ISSUE TITLE
Compile to one pdf only

### ISSUE THREAD

**Issue by jbonigomes** [dharFr/grunt-wkhtmltopdf#13]
Is there an option to compile all my html files to one pdf only?

**Comment by dharFr** [comment]
Not possible right now.
But it looks like `wkhtml2pdf` tool accepts merging multiple html inputs to one pdf output. I guess it would be possible add an option for `dest` to be considered as a single file instead of an output directory.

**Comment by jbonigomes** [comment]
Thanks dharFr, it works fine for me for the moment, not a deal breaker, have a good weekend.
